version: '3.1'
services:
  web:
    image: nginx
    depends_on:
      - db
    ports:
      - "8069:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
  backend:
    image: odoo:15.0
    depends_on:
      - db
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      - ./addons:/mnt/extra-addons
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
volumes:
  odoo-web-data:
  odoo-db-data:
